### PR TITLE
attempt to fix #3 (allow to configure service manually)

### LINKED ISSUE #3: ability to set the service to disabled
Hi, 

have you thought of adding the ability to decide if the service for the 'kafka::broker' is enabled or disabled? that way we could use a different system / custom script (i.e.  upstart / systemd ) to manage the service for the broker if we wanted to.

### PR DESCRIPTION
**Pull request by feniix**
we would like to add the ability to completely skip the service creation/install and be able to set the state to stopped or running.

### CODE REVIEW

**Comment by jyaworski** [comment]
Hello:

What's the status of this PR?

**Comment by bastelfreak** [comment]
@feniix hi, are you still interested in this PR? could you rebase it?

**Comment by feniix** [comment]
@bastelfreak I just rebased and pushed again

**Comment by feniix** [comment]
I am looking into the failing tests

**Comment by dhoppe** [comment]
@bastelfreak Not so fast. A lot of these files will change with PR #46.

**Comment by bastelfreak** [comment]
@feniix sorry to ping you again :(

**Comment by feniix** [comment]
Here we go again

**Pull request merged**
