### PR TITLE
[WIP] enable acceptance tests

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
I don't know if they work at all and which platform constrains they have, so I started with everything and will have a look later. CC: @bjoernhaeuser

**Comment by bastelfreak** [comment]
@bjoernhaeuser can you have a look please? There are some issues for downloading kafka and I suppose they are related to your PR #263

**Comment by bjoernhaeuser** [comment]
@bastelfreak taking the log from the build:

```
ubuntu1404-64-1 22:03:21$ puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.QGFb14
  Info: Loading facts
  Info: Loading facts
  Info: Loading facts
  Info: Loading facts
  Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
     (in /etc/puppetlabs/puppet/hiera.yaml)
  Notice: Compiled catalog for ubuntu1404-64-1.c.eco-emissary-99515.internal in environment production in 0.48 seconds
  Info: Applying configuration version '1530828204'
  Notice: /Stage[main]/Kafka/File[/opt/kafka-2.11-0.8.2.2]/ensure: created
  Notice: /Stage[main]/Kafka/File[/opt/kafka]/target: target changed '/opt/kafka-2.11-0.11.0.1' to '/opt/kafka-2.11-0.8.2.2'
  Error: Execution of '/usr/bin/curl https://www.apache.org/dyn/closer.lua?action=download&filename=kafka/0.11.0.1/kafka_2.11-0.8.2.2.tgz -o /tmp/kafka_2.11-0.8.2.2.tgz_20180705-5150-h7zjwz -fsSL --max-redirs 5' returned 22: curl: (22) The requested URL returned error: 404 Not Found
  Error: /Stage[main]/Kafka/Archive[/var/tmp/kafka/kafka_2.11-0.8.2.2.tgz]/ensure: change from absent to present failed: Execution of '/usr/bin/curl https://www.apache.org/dyn/closer.lua?action=download&filename=kafka/0.11.0.1/kafka_2.11-0.8.2.2.tgz -o /tmp/kafka_2.11-0.8.2.2.tgz_20180705-5150-h7zjwz -fsSL --max-redirs 5' returned 22: curl: (22) The requested URL returned error: 404 Not Found
```

This is the problem I mentioned in #257. It is using different versions in parts for the url. Also we need to replace 0.8.2.2 with a newer version, because its not on all mirrors anymore :(

**Comment by bastelfreak** [comment]
@bjoernhaeuser are you able to provide a patch for this?

**Pull request merged**
