### PR TITLE
fix init script to actually check status

### PR DESCRIPTION
**Pull request by fessyfoo**
flip sense of the check that pid in pid file matches pid in process
list.

### CODE REVIEW

**Comment by igalic** [comment]
is this the same as #96 ?

**Comment by fessyfoo** [comment]
#96 was  a merge to a different branch.     there was some confusion around opentable/puppet-kafka being renamed to voxpupuli/puppet-kafka  and the magic redirecting github does.

**Comment by fessyfoo** [comment]
this is  a less comprehensive version of #94

**Comment by fessyfoo** [comment]
FWIW we reforked opentable/puppet-kafka   so we have our own fork again.   [ voxpupli was a transfer owner ship of opentable/puppet-kafka and when the branch `no-zookeper-dep` was pushed to opentable/puppet-kafka  it showed up on voxpupli/puppet-kafka ....

blah hope that makes sense,  sorry for adding confusion.

**Pull request closed without merging**
