### PR TITLE
allow latest dependencies

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
requires a new puppetlabs-java release

**Comment by martin-koerner** [comment]
You are probably already aware of this, but just to be sure: systemd v3.0.0 breaks e.g. broker::service because it still references `Exec['systemctl-daemon-reload']` which was removed in https://github.com/camptocamp/puppet-systemd/pull/171.

**Comment by kenyon** [comment]
I think this needs https://github.com/deric/puppet-zookeeper/pull/171 now.

**Review by kenyon — APPROVED** [review]
Tests now pass!

**Review by smortex — APPROVED** [review]

**Pull request merged**
