### PR TITLE
Use module voxpupuli/archive instead of wget. This should fix #31

### LINKED ISSUE #31: stop trying to make fetch happen
stop trying to make fetch happen. it's not going to happen!

@voxpupuli has [puppet-archive](https://github.com/voxpupuli/puppet-archive/) which abstracts away this ad-hoc implementation of fetch, I mean wget. we should use that instead.

i realize that this is a breaking change, but perhaps it is for the better.

### PR DESCRIPTION
**Pull request by dhoppe**
Please merge.

### CODE REVIEW

**Comment by igalic** [comment]
i was going to suggest adding checksum verification, but, what the heck is this checksum format??
https://dist.apache.org/repos/dist/release/kafka/0.9.0.1/

**Comment by dhoppe** [comment]
I think this makes no sense, because there are multiple combinations of Kafka and Scala versions possible.

**Comment by igalic** [comment]
we can build the checksum url the same way we build the download url (except we'd have to use dist.apache.org rather than a mirror)

**Comment by dhoppe** [comment]
@igalic I am happy to merge, if you create a pull request. ;)

**Pull request merged**
