### PR TITLE
modulesync 2.11.0

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 1.9.6

### CODE REVIEW

**Comment by bastelfreak** [comment]
We need to wait for a new puppetlabs/java release. 3.0.0 cannot handle stdlib 5....

**Comment by bastelfreak** [comment]
Requested a release in https://tickets.puppetlabs.com/browse/MODULES-7745

**Comment by Bialogs** [comment]
@bastelfreak They've released https://github.com/puppetlabs/puppetlabs-java/tree/3.1.0

**Comment by bastelfreak** [comment]
*sigh* this depends on https://github.com/deric/puppet-zookeeper/pull/116

**Comment by Bialogs** [comment]
https://github.com/deric/puppet-zookeeper/pull/116 is merged.

**Comment by bastelfreak** [comment]
this now fails because of the legacy beaker3 stuff that tries to setup hiera...

**Comment by dhoppe** [comment]
Now we have an dependency problem related to deric/zookeeper. :(

**Pull request closed without merging**
