### PR TITLE
changed limit_nofile from Integer to String

### PR DESCRIPTION
**Pull request by LionelCons**
This fixes https://github.com/voxpupuli/puppet-kafka/issues/228.

### CODE REVIEW

**Comment by wyardley** [comment]
Maybe a better fix would be something like `Variant[Integer, Enum['infinity', 'unlimited']]` (or whatever values are valid?

**Comment by LionelCons** [comment]
@wyardley systemd's syntax also allows setting soft and hard limits at the same time with something like `LimitNOFILE=	1024:2048`. Full type validation would be too complex in this module.

**Comment by alexjfisher** [comment]
Should still probably allow Integers as well as any string?

**Comment by LionelCons** [comment]
@alexjfisher In this case other parameters (for instance `TimeoutStopSec` aka `timeout_stop`) should also be changed...

**Comment by LionelCons** [comment]
@bastelfreak Since you approved this one, could you please merge it? Thanks!

**Comment by wyardley** [comment]
I agree with @alexjfisher's suggestion about adding integer as valid too (this would also make it backwards-compatible again)... I know this is merged, but maybe someone would want to implement this as a separate PR?

**Pull request merged**
