### PR TITLE
Release 3.1.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
don't merge yet

**Comment by LionelCons** [comment]
FWIW, I can confirm that the problem with Puppet 5 was present in version 3.0.0 already.

**Comment by LionelCons** [comment]
What is blocking this 3.1.0? I would be happy to help getting this new release out...

**Comment by bastelfreak** [comment]
HI @LionelCons, I pushed the release to the forge

**Pull request merged**
