### PR TITLE
Add custom config dir

### PR DESCRIPTION
**Pull request by antyale**
Hello,

This PR allow the customization of the kafka configuration dir.
I had some issues with bundler v1.14 and ruby 1.9.3 [link](https://travis-ci.org/voxpupuli/puppet-kafka/builds/199275598). Using bundler v.1.13 everything works fine...

Thanks!

### CODE REVIEW

**Comment by dhoppe** [comment]
This PR looks great, but the changes regarding `.travis.yml` will be changes back by `modulesync`. Maybe this needs to be addressed as separate PR.

**Comment by antyale** [comment]
Great, I have removed the changes in `.travis.yml`. 
I will rebase this PR once the modulesync is updated.

**Comment by bastelfreak** [comment]
@antyale could you please rebase?

**Comment by antyale** [comment]
@bastelfreak Done, 
Cheers!

**Pull request merged**
