### PR TITLE
Adding support to KAFKA_HEAP_OPTS

### PR DESCRIPTION
**Pull request by ortz**
Hey,

We're missing the ability to modify KAFKA HEAP OPTS, I hope this PR would be sufficient to add this support.

Thanks,

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @ortz, thanks for the contribution. How does $heap_opts and $gc_opts differ? The both have the same defaults. Does kafka handles these environment variables differently?

**Comment by ortz** [comment]
Yes it does, if you'll take a look at kafka-start.sh it checks this env
variable and applies it if exists.

**Comment by bastelfreak** [comment]
Alright. Could you also add tests for the new variable please?

**Comment by ortz** [comment]
Yes, I'll add it tomorrow when I'll be at the office

**Comment by ortz** [comment]
Hey @bastelfreak, I've added the tests.
What are the chances you'll accept the pull request and release a new version today ?
(In my project I also need CentOS7 support but it's missing in the latest release, it is merged to master though)

**Comment by bjoernhaeuser** [comment]
Hey,

isnt that handled through GC opts?

**Comment by ortz** [comment]
No, it doesn't look like that (https://apache.googlesource.com/kafka/+/trunk/bin/kafka-server-start.sh).

I couldn't find GC_OPTS in the server start file and HEAP_OPTS is been used.

**Comment by bjoernhaeuser** [comment]
But then we need to remove the gc opts when they are not set.

**Comment by DjxDeaf** [comment]
@bjoernhaeuser maybe you meant "KAFKA_GC_LOG_OPTS" which is being used in the bin/kafka-run-class.sh but leaving it empty is just fine, and setting the other params are a not related and quite important

**Comment by bastelfreak** [comment]
thanks for the contribution!

**Pull request merged**
